#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libyubikey
Version  : 1.13
Release  : 1
URL      : https://github.com/Yubico/yubico-c/archive/libyubikey-1.13.tar.gz
Source0  : https://github.com/Yubico/yubico-c/archive/libyubikey-1.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: libyubikey-bin = %{version}-%{release}
Requires: libyubikey-lib = %{version}-%{release}
Requires: libyubikey-license = %{version}-%{release}
Requires: libyubikey-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : valgrind

%description
YubiKey C Library: libyubikey
=============================
This package make up the low-level C software development kit for the
Yubico https://www.yubico.com[YubiKey] authentication device.

%package bin
Summary: bin components for the libyubikey package.
Group: Binaries
Requires: libyubikey-license = %{version}-%{release}

%description bin
bin components for the libyubikey package.


%package dev
Summary: dev components for the libyubikey package.
Group: Development
Requires: libyubikey-lib = %{version}-%{release}
Requires: libyubikey-bin = %{version}-%{release}
Provides: libyubikey-devel = %{version}-%{release}
Requires: libyubikey = %{version}-%{release}

%description dev
dev components for the libyubikey package.


%package lib
Summary: lib components for the libyubikey package.
Group: Libraries
Requires: libyubikey-license = %{version}-%{release}

%description lib
lib components for the libyubikey package.


%package license
Summary: license components for the libyubikey package.
Group: Default

%description license
license components for the libyubikey package.


%package man
Summary: man components for the libyubikey package.
Group: Default

%description man
man components for the libyubikey package.


%prep
%setup -q -n yubico-c-libyubikey-1.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571709829
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1571709829
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libyubikey
cp COPYING %{buildroot}/usr/share/package-licenses/libyubikey/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/modhex
/usr/bin/ykgenerate
/usr/bin/ykparse

%files dev
%defattr(-,root,root,-)
/usr/include/yubikey.h
/usr/lib64/libyubikey.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libyubikey.so.0
/usr/lib64/libyubikey.so.0.1.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libyubikey/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/modhex.1
/usr/share/man/man1/ykgenerate.1
/usr/share/man/man1/ykparse.1
